# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.4.5
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "GetSearchedStatsUsernamesByDiscordIdRow",
    "QueryResults",
    "add_command_usage",
    "get_searched_stats_usernames_by_discord_id",
)

import dataclasses
import operator
import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import asyncpg.cursor
    import collections.abc

    QueryResultsArgsType: typing.TypeAlias = int | float | str | memoryview | None

    ConnectionLike: typing.TypeAlias = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]

from src.common.db import models


@dataclasses.dataclass()
class GetSearchedStatsUsernamesByDiscordIdRow:
    username: typing.Any | None
    search_count: int


ADD_COMMAND_USAGE: typing.Final[str] = """-- name: AddCommandUsage :exec
INSERT INTO
  command_usage (command_name, discord_id, arguments)
VALUES
  ($1, $2, $3)
"""

GET_SEARCHED_STATS_USERNAMES_BY_DISCORD_ID: typing.Final[str] = """-- name: GetSearchedStatsUsernamesByDiscordId :many
SELECT
  arguments ->> 'username' AS username,
  COUNT(*) AS search_count
FROM
  command_usage
WHERE
  discord_id = $1
  AND command_name = 'stats'
  AND arguments ->> 'username' IS NOT NULL
GROUP BY
  arguments ->> 'username'
ORDER BY
  search_count DESC
LIMIT
  $2
"""


T = typing.TypeVar("T")


class QueryResults(typing.Generic[T]):
    __slots__ = ("_args", "_conn", "_cursor", "_decode_hook", "_iterator", "_sql")

    def __init__(
        self,
        conn: ConnectionLike,
        sql: str,
        decode_hook: collections.abc.Callable[[asyncpg.Record], T],
        *args: QueryResultsArgsType,
    ) -> None:
        self._conn = conn
        self._sql = sql
        self._decode_hook = decode_hook
        self._args = args
        self._cursor: asyncpg.cursor.CursorFactory[asyncpg.Record] | None = None
        self._iterator: asyncpg.cursor.CursorIterator[asyncpg.Record] | None = None

    def __aiter__(self) -> QueryResults[T]:
        return self

    def __await__(
        self,
    ) -> collections.abc.Generator[None, None, collections.abc.Sequence[T]]:
        async def _wrapper() -> collections.abc.Sequence[T]:
            result = await self._conn.fetch(self._sql, *self._args)
            return [self._decode_hook(row) for row in result]
        return _wrapper().__await__()

    async def __anext__(self) -> T:
        if self._cursor is None or self._iterator is None:
            self._cursor = self._conn.cursor(self._sql, *self._args)
            self._iterator = self._cursor.__aiter__()
        try:
            record = await self._iterator.__anext__()
        except StopAsyncIteration:
            self._cursor = None
            self._iterator = None
            raise
        return self._decode_hook(record)


async def add_command_usage(conn: ConnectionLike, *, command_name: str, discord_id: int, arguments: str | None) -> None:
    await conn.execute(ADD_COMMAND_USAGE, command_name, discord_id, arguments)


def get_searched_stats_usernames_by_discord_id(conn: ConnectionLike, *, discord_id: int, limit: int) -> QueryResults[GetSearchedStatsUsernamesByDiscordIdRow]:
    def _decode_hook(row: asyncpg.Record) -> GetSearchedStatsUsernamesByDiscordIdRow:
        return GetSearchedStatsUsernamesByDiscordIdRow(username=row[0], search_count=row[1])
    return QueryResults[GetSearchedStatsUsernamesByDiscordIdRow](conn, GET_SEARCHED_STATS_USERNAMES_BY_DISCORD_ID, _decode_hook, discord_id, limit)
