# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.4.5
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "add_creator",
    "get_creator",
)

import dataclasses
import operator
import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import asyncpg.cursor
    import collections.abc
    import datetime

    QueryResultsArgsType: typing.TypeAlias = int | float | str | memoryview | datetime.date | datetime.time | datetime.datetime | datetime.timedelta | None

    ConnectionLike: typing.TypeAlias = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]

from src.common.db import models


ADD_CREATOR: typing.Final[str] = """-- name: AddCreator :one
INSERT INTO
  creators (discord_id, since)
VALUES
  ($1, $2)
RETURNING
  discord_id, since
"""

GET_CREATOR: typing.Final[str] = """-- name: GetCreator :one
SELECT
  discord_id, since
FROM
  creators
WHERE
  discord_id = $1
"""


async def add_creator(conn: ConnectionLike, *, discord_id: int, since: float | None) -> models.Creator | None:
    row = await conn.fetchrow(ADD_CREATOR, discord_id, since)
    if row is None:
        return None
    return models.Creator(discord_id=row[0], since=row[1])


async def get_creator(conn: ConnectionLike, *, discord_id: int) -> models.Creator | None:
    row = await conn.fetchrow(GET_CREATOR, discord_id)
    if row is None:
        return None
    return models.Creator(discord_id=row[0], since=row[1])
