# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.4.5
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "create_game_stats_record",
    "get_latest_game_stats",
)

import dataclasses
import operator
import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import asyncpg.cursor
    import collections.abc
    import datetime

    QueryResultsArgsType: typing.TypeAlias = int | float | str | memoryview | datetime.date | datetime.time | datetime.datetime | datetime.timedelta | None

    ConnectionLike: typing.TypeAlias = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]

from src.common.db import models


CREATE_GAME_STATS_RECORD: typing.Final[str] = """-- name: CreateGameStatsRecord :exec
INSERT INTO
  game_stats (playing, visits)
VALUES
  ($1, $2)
"""

GET_LATEST_GAME_STATS: typing.Final[str] = """-- name: GetLatestGameStats :one
SELECT
  id, playing, visits, recorded_at
FROM
  game_stats
ORDER BY
  recorded_at DESC
LIMIT
  1
"""


async def create_game_stats_record(conn: ConnectionLike, *, playing: int, visits: int) -> None:
    await conn.execute(CREATE_GAME_STATS_RECORD, playing, visits)


async def get_latest_game_stats(conn: ConnectionLike) -> models.GameStat | None:
    row = await conn.fetchrow(GET_LATEST_GAME_STATS)
    if row is None:
        return None
    return models.GameStat(id=row[0], playing=row[1], visits=row[2], recorded_at=row[3])
