# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.4.5
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "create_game_stats_record",
)

import dataclasses
import operator
import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import asyncpg.cursor
    import collections.abc
    import datetime

    QueryResultsArgsType: typing.TypeAlias = int | float | str | memoryview | datetime.date | datetime.time | datetime.datetime | datetime.timedelta | None

    ConnectionLike: typing.TypeAlias = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]

from src.common.db import models


CREATE_GAME_STATS_RECORD: typing.Final[str] = """-- name: CreateGameStatsRecord :exec
INSERT INTO
  game_stats (playing, visits)
VALUES
  ($1, $2)
"""


async def create_game_stats_record(conn: ConnectionLike, *, playing: int, visits: int) -> None:
    await conn.execute(CREATE_GAME_STATS_RECORD, playing, visits)
