# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.4.5
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "get_leaderboards_cache",
    "upsert_leaderboards_cache",
)

import dataclasses
import operator
import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import asyncpg.cursor
    import collections.abc
    import datetime

    QueryResultsArgsType: typing.TypeAlias = int | float | str | memoryview | datetime.date | datetime.time | datetime.datetime | datetime.timedelta | None

    ConnectionLike: typing.TypeAlias = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]

from src.common.db import models


GET_LEADERBOARDS_CACHE: typing.Final[str] = """-- name: GetLeaderboardsCache :one
SELECT
  period, leaderboard_data, refreshed_at
FROM
  leaderboards_cache
WHERE
  period = $1
"""

UPSERT_LEADERBOARDS_CACHE: typing.Final[str] = """-- name: UpsertLeaderboardsCache :exec
INSERT INTO
  leaderboards_cache (period, leaderboard_data)
VALUES
  ($1, $2)
ON CONFLICT (period) DO UPDATE
SET
  leaderboard_data = EXCLUDED.leaderboard_data,
  refreshed_at = NOW()
"""


async def get_leaderboards_cache(conn: ConnectionLike, *, period: str) -> models.LeaderboardsCache | None:
    row = await conn.fetchrow(GET_LEADERBOARDS_CACHE, period)
    if row is None:
        return None
    return models.LeaderboardsCache(period=row[0], leaderboard_data=row[1], refreshed_at=row[2])


async def upsert_leaderboards_cache(conn: ConnectionLike, *, period: str, leaderboard_data: str) -> None:
    await conn.execute(UPSERT_LEADERBOARDS_CACHE, period, leaderboard_data)
