# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.4.5
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "CommandUsage",
    "Creator",
    "RobloxUsernameCache",
    "ScheduledTournament",
)

import dataclasses
import typing

if typing.TYPE_CHECKING:
    import collections.abc
    import datetime


@dataclasses.dataclass()
class CommandUsage:
    id: int
    command_name: str
    discord_id: int
    arguments: str | None
    executed_at: datetime.datetime | None


@dataclasses.dataclass()
class Creator:
    discord_id: int
    since: float | None


@dataclasses.dataclass()
class RobloxUsernameCache:
    user_id: int
    username: str
    updated_at: datetime.datetime | None


@dataclasses.dataclass()
class ScheduledTournament:
    id: int
    server_code: int
    scheduled_at: datetime.datetime
    ends_at: datetime.datetime | None
    state: int
