# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.4.5
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "get_player_stats_cache",
    "upsert_player_stats_cache",
)

import dataclasses
import operator
import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import asyncpg.cursor
    import collections.abc
    import datetime

    QueryResultsArgsType: typing.TypeAlias = int | float | str | memoryview | datetime.date | datetime.time | datetime.datetime | datetime.timedelta | None

    ConnectionLike: typing.TypeAlias = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]

from src.common.db import models


GET_PLAYER_STATS_CACHE: typing.Final[str] = """-- name: GetPlayerStatsCache :one
SELECT
  user_id, stats, refreshed_at
FROM
  player_stats_cache
WHERE
  user_id = $1
"""

UPSERT_PLAYER_STATS_CACHE: typing.Final[str] = """-- name: UpsertPlayerStatsCache :exec
INSERT INTO
  player_stats_cache (user_id, stats)
VALUES
  ($1, $2)
ON CONFLICT (user_id) DO UPDATE
SET
  stats = EXCLUDED.stats,
  refreshed_at = NOW()
"""


async def get_player_stats_cache(conn: ConnectionLike, *, user_id: int) -> models.PlayerStatsCache | None:
    row = await conn.fetchrow(GET_PLAYER_STATS_CACHE, user_id)
    if row is None:
        return None
    return models.PlayerStatsCache(user_id=row[0], stats=row[1], refreshed_at=row[2])


async def upsert_player_stats_cache(conn: ConnectionLike, *, user_id: int, stats: str) -> None:
    await conn.execute(UPSERT_PLAYER_STATS_CACHE, user_id, stats)
