# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.4.5
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "QueryResults",
    "add_scheduled_tournament",
    "delete_scheduled_tournament",
    "get_upcoming_or_ongoing_tournaments",
    "update_tournament_state",
)

import dataclasses
import operator
import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import asyncpg.cursor
    import collections.abc
    import datetime

    QueryResultsArgsType: typing.TypeAlias = int | float | str | memoryview | datetime.date | datetime.time | datetime.datetime | datetime.timedelta | None

    ConnectionLike: typing.TypeAlias = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]

from src.common.db import models


ADD_SCHEDULED_TOURNAMENT: typing.Final[str] = """-- name: AddScheduledTournament :exec
INSERT INTO
  scheduled_tournaments (server_code, scheduled_at, ends_at, state)
VALUES
  (
    $1,
    $2,
    $3,
    $4
  )
"""

DELETE_SCHEDULED_TOURNAMENT: typing.Final[str] = """-- name: DeleteScheduledTournament :exec
DELETE FROM scheduled_tournaments
WHERE
  (
    server_code = $1
    AND scheduled_at = $2
  )
"""

GET_UPCOMING_OR_ONGOING_TOURNAMENTS: typing.Final[str] = """-- name: GetUpcomingOrOngoingTournaments :many
SELECT
  id, server_code, scheduled_at, ends_at, state
FROM
  scheduled_tournaments
WHERE
  state = 0
  OR state = 1
"""

UPDATE_TOURNAMENT_STATE: typing.Final[str] = """-- name: UpdateTournamentState :exec
UPDATE scheduled_tournaments
SET
  state = $2
WHERE
  id = $1
"""


T = typing.TypeVar("T")


class QueryResults(typing.Generic[T]):
    __slots__ = ("_args", "_conn", "_cursor", "_decode_hook", "_iterator", "_sql")

    def __init__(
        self,
        conn: ConnectionLike,
        sql: str,
        decode_hook: collections.abc.Callable[[asyncpg.Record], T],
        *args: QueryResultsArgsType,
    ) -> None:
        self._conn = conn
        self._sql = sql
        self._decode_hook = decode_hook
        self._args = args
        self._cursor: asyncpg.cursor.CursorFactory[asyncpg.Record] | None = None
        self._iterator: asyncpg.cursor.CursorIterator[asyncpg.Record] | None = None

    def __aiter__(self) -> QueryResults[T]:
        return self

    def __await__(
        self,
    ) -> collections.abc.Generator[None, None, collections.abc.Sequence[T]]:
        async def _wrapper() -> collections.abc.Sequence[T]:
            result = await self._conn.fetch(self._sql, *self._args)
            return [self._decode_hook(row) for row in result]
        return _wrapper().__await__()

    async def __anext__(self) -> T:
        if self._cursor is None or self._iterator is None:
            self._cursor = self._conn.cursor(self._sql, *self._args)
            self._iterator = self._cursor.__aiter__()
        try:
            record = await self._iterator.__anext__()
        except StopAsyncIteration:
            self._cursor = None
            self._iterator = None
            raise
        return self._decode_hook(record)


async def add_scheduled_tournament(conn: ConnectionLike, *, server_code: int, scheduled_at: datetime.datetime, ends_at: datetime.datetime | None, state: int | None) -> None:
    await conn.execute(ADD_SCHEDULED_TOURNAMENT, server_code, scheduled_at, ends_at, state)


async def delete_scheduled_tournament(conn: ConnectionLike, *, server_code: int, scheduled_at: datetime.datetime) -> None:
    await conn.execute(DELETE_SCHEDULED_TOURNAMENT, server_code, scheduled_at)


def get_upcoming_or_ongoing_tournaments(conn: ConnectionLike) -> QueryResults[models.ScheduledTournament]:
    def _decode_hook(row: asyncpg.Record) -> models.ScheduledTournament:
        return models.ScheduledTournament(id=row[0], server_code=row[1], scheduled_at=row[2], ends_at=row[3], state=row[4])
    return QueryResults[models.ScheduledTournament](conn, GET_UPCOMING_OR_ONGOING_TOURNAMENTS, _decode_hook)


async def update_tournament_state(conn: ConnectionLike, *, id_: int, state: int) -> None:
    await conn.execute(UPDATE_TOURNAMENT_STATE, id_, state)
