# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.4.5
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "get_cached_username",
    "upsert_username",
)

import dataclasses
import operator
import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import asyncpg.cursor
    import collections.abc
    import datetime

    QueryResultsArgsType: typing.TypeAlias = int | float | str | memoryview | datetime.date | datetime.time | datetime.datetime | datetime.timedelta | None

    ConnectionLike: typing.TypeAlias = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]

from src.common.db import models


GET_CACHED_USERNAME: typing.Final[str] = """-- name: GetCachedUsername :one
SELECT
  user_id, username, updated_at
FROM
  roblox_username_cache
WHERE
  user_id = $1
"""

UPSERT_USERNAME: typing.Final[str] = """-- name: UpsertUsername :exec
INSERT INTO
  roblox_username_cache (user_id, username)
VALUES
  ($1, $2)
ON CONFLICT (user_id) DO UPDATE
SET
  username = EXCLUDED.username,
  updated_at = NOW()
"""


async def get_cached_username(conn: ConnectionLike, *, user_id: int) -> models.RobloxUsernameCache | None:
    row = await conn.fetchrow(GET_CACHED_USERNAME, user_id)
    if row is None:
        return None
    return models.RobloxUsernameCache(user_id=row[0], username=row[1], updated_at=row[2])


async def upsert_username(conn: ConnectionLike, *, user_id: int, username: str) -> None:
    await conn.execute(UPSERT_USERNAME, user_id, username)
